 CREATE TABLE IF NOT EXISTS job_applications (
        id SERIAL PRIMARY KEY,
        reference_id VARCHAR(15) UNIQUE NOT NULL,
        full_name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        mobile_number VARCHAR(10) UNIQUE NOT NULL,
        department VARCHAR(50) NOT NULL,
        job_role VARCHAR(50) NOT NULL,
        status VARCHAR(20) DEFAULT 'Pending',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ssc_doc_path VARCHAR(255),
        intermediate_doc_path VARCHAR(255),
        graduation_doc_path VARCHAR(255),
        offer_letter_path VARCHAR(255),
        dob DATE,
        father_name VARCHAR(100),
        permanent_address VARCHAR(255),
        expected_salary INTEGER,
        interview_date DATE,
        joining_date VARCHAR(50),
        employment_type VARCHAR(50),
        branch_location VARCHAR(50),
        ssc_year INTEGER,
        ssc_percentage VARCHAR(10),
        intermediate_year INTEGER,
        intermediate_percentage VARCHAR(10),
        college_name VARCHAR(100),
        register_number VARCHAR(20),
        graduation_year INTEGER,
        graduation_percentage VARCHAR(10),
        additional_certifications TEXT,
        additional_files_path VARCHAR(255),
        experience_status VARCHAR(20),
        years_of_experience INTEGER,
        previous_company VARCHAR(100),
        previous_job_role VARCHAR(50)
      );